# Generated by Django 4.2.11 on 2024-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="minimum_amount",
            field=models.IntegerField(default=2500),
        ),
    ]
