# Generated by Django 4.2.11 on 2024-05-20 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_order_remove_cartitems_color_variant"),
        ("products", "0004_alter_coupon_minimum_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color_variant",
        ),
        migrations.DeleteModel(
            name="ColorVariant",
        ),
    ]
